---
title: "data_wrangle_Exp1_memory"
author: "Jen Yang"
date: "2025-1-20, last modified 2025-1-24"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    hightlight: zenburn
    toc_depth: 6
---

# note
date created: 3-16-2024 by Jen Yang
date last modified: 3-16-2024 by Jen Yang
generate tsv from json
```{r clean, include=FALSE}
# clean environment
rm(list = ls())
```

```{r restart R session, include=FALSE, results='hide'}
# .rs.restartR()
```

# Load libraries
```{r libraries, message=FALSE, warning=TRUE, include=FALSE}
library(car)
library(plyr)
library(foreign)
library(pscl)
library(boot)
library(MASS)
library(robust)
library(sfsmisc)
library(ggplot2)
library(reshape2)
library(ppcor)
library(ggrepel)
library(Hmisc)
library(tidyverse)
library(sandwich)
library(ggpubr)
library(interactions)
library(knitr)
library(twowaytests)
library(ggfortify)
library(interactions)
library(broom)
library(patchwork)
library(robustbase)
library(lmtest)
library(modelr)
library(Rmisc)
# library(raincloudplots)
library(cowplot)
library(readr)
library(PupillometryR)
library(ggpp)
library(estimatr)
library(skedastic)
library(ggpubr)
library(lubridate)
library(readxl)
library(gridExtra)
library(scales)
library(rstudioapi)

library(jsonlite)
library(rjson)
library(readr)
```

# memory pdf and excel folder
```{r}
memory_path = "/Users/momocco/Documents/GitHub/risk-ambiguity/data/Exp1/memory"
taskdata_google_dir = "/Users/momocco/Library/CloudStorage/GoogleDrive-tun51150@temple.edu/.shortcut-targets-by-id/1Yd_mABZr2-erO8s2c0GuJSs36TfUycDa/Limited_Info/Experiment_1/risk_amb/data/subject_data_compressed"

OSF_exp1_dir = "/Users/momocco/Documents/GitHub/risk-ambiguity/dissenminate/OSF_upload/beh_risk_amb_Exp1"
phenotype_exp1_dir = paste(OSF_exp1_dir, "phenotype", sep = "/")
```

# create participant list based on data availability
```{r}
sub_googledata_list <- list.dirs(path = taskdata_google_dir, full.names = FALSE, recursive = FALSE)
```

# extract memory tsv
## create empty dataframes to save data
```{r}
color_best_worst_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = 3))
colnames(color_best_worst_df) = c("participant_id", "best_lot", "worst_lot")

win_count_names = c("participant_id", "percent_0", "percent_10", "percent_20", "percent_30", "percent_40", "percent_50", "percent_60", "percent_70", "percent_80", "percent_90", "percent_100")

red_win_count_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = length(win_count_names)))
colnames(red_win_count_df) = win_count_names

green_win_count_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = length(win_count_names)))
colnames(green_win_count_df) = win_count_names

blue_win_count_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = length(win_count_names)))
colnames(blue_win_count_df) = win_count_names
  
accept_percentage_count_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = length(win_count_names)))
colnames(accept_percentage_count_df) = win_count_names

yellow_seen_count_df = data.frame(matrix(nrow = length(sub_googledata_list), ncol = length(win_count_names)))
colnames(yellow_seen_count_df) = win_count_names
```

## extract data from excels
```{r}
for (f in 1:length(sub_googledata_list)) {
  # f = 16
  print(f)
  participant_f = sub_googledata_list[f]
  print(participant_f)
  
  participant_f_num <- str_extract_all(participant_f, "\\d+")[[1]]
  mem_f_xlsx_name = paste(participant_f_num, "ManipulationCheck.xlsx", sep = "_")
  mem_f_xlsx_path = paste(memory_path, mem_f_xlsx_name, sep = "/")
  
  if (file.exists(mem_f_xlsx_path)) {
    mem_f_df = read_excel(mem_f_xlsx_path, .name_repair = "unique_quiet")
    
    if (is.na(mem_f_df[1,1]) == FALSE & mem_f_df[1,1] == "Subj#") {
      
      # remove rows with all NAs
      mem_f_df <- mem_f_df[rowSums(!is.na(mem_f_df)) > 0, ]
      mem_f_df = as.data.frame(mem_f_df, )
      
      # extract best and worst lottery color
      color_best_worst_df$participant_id[f] = participant_f
      color_best_worst_df$best_lot[f] = mem_f_df[2,1]
      color_best_worst_df$worst_lot[f] = mem_f_df[4,1]
      
      # extract times per winning chance per color
      ## red
      red_win_count_df$participant_id[f] = participant_f
      red_f_df = mem_f_df[c(6,7),] %>% .[, colSums(!is.na(.)) > 0]
      red_win_count_df[f,-1] = red_f_df[2,c(2:12)]
      ## green
      green_win_count_df$participant_id[f] = participant_f
      green_f_df = mem_f_df[c(6,8),] %>% .[, colSums(!is.na(.)) > 0]
      green_win_count_df[f,-1] = green_f_df[2,c(2:12)]
      ## blue
      blue_win_count_df$participant_id[f] = participant_f
      blue_f_df = mem_f_df[c(6,9),] %>% .[, colSums(!is.na(.)) > 0]
      blue_win_count_df[f,-1] = blue_f_df[2,c(2:12)]
      
      # extract "On a scale of 1-10 how often do you think you accepted lotteries with the given chances of winning?"
      accept_percentage_count_df$participant_id[f] = participant_f
      accept_percentage_count_f_df = mem_f_df[c(11,12),] %>% .[, colSums(!is.na(.)) > 0]
      accept_percentage_count_df[f,-1] = accept_percentage_count_f_df[2,]
      
      # extract "In part 2 you will have one more lottery that you haven’t seen before, Yellow. Use your gut to tell how often you think the Yellow lottery would have had the given chances of winning, if you had seen it in Part 1."
      yellow_seen_count_df$participant_id[f] = participant_f
      yellow_seen_count_f_df = mem_f_df[c(14,15),] %>% .[, colSums(!is.na(.)) > 0]
      yellow_seen_count_df[f,-1] = yellow_seen_count_f_df[2,c(2:12)]
    } else {
      print(paste(mem_f_xlsx_path, " exists but empty.", sep = ""))
    }
  } else {
    print(paste(mem_f_xlsx_path, "doesn't exist", sep = " "))
  }
}
```


# filter based on final participant list and save to OSF
## load final participant list
```{r}
exp1_sub_list = read_tsv(paste(OSF_exp1_dir, "participants.tsv", sep = "/"), show_col_types = F) %>% 
  select(participant_id)
```

## filter and save
```{r}
color_best_worst_df = color_best_worst_df %>% na.omit() %>% 
  mutate(best_lot = tolower(best_lot),
         worst_lot = tolower(worst_lot))
# filter out subs who didn't respond color properly
color_best_worst_df = 
  color_best_worst_df[color_best_worst_df$best_lot %in% c("red", "blue", "green") & color_best_worst_df$worst_lot %in% c("red", "blue", "green"), ]

mem_sub_list = intersect(color_best_worst_df$participant_id, exp1_sub_list$participant_id)

color_best_worst_df = merge(exp1_sub_list, color_best_worst_df, by.x = TRUE, all.x = TRUE)
# color_best_worst_df = color_best_worst_df[color_best_worst_df$participant_id %in% mem_sub_list, ]
write_tsv(color_best_worst_df, paste(phenotype_exp1_dir, "color_best_worst.tsv", sep = "/"))

red_win_count_df = merge(exp1_sub_list, red_win_count_df, by.x = TRUE, all.x = TRUE)
# red_win_count_df = red_win_count_df[red_win_count_df$participant_id %in% mem_sub_list, ]
write_tsv(red_win_count_df, paste(phenotype_exp1_dir, "red_win_count.tsv", sep = "/"))

green_win_count_df = merge(exp1_sub_list, green_win_count_df, by.x = TRUE, all.x = TRUE)
# green_win_count_df = green_win_count_df[green_win_count_df$participant_id %in% mem_sub_list, ]
write_tsv(green_win_count_df, paste(phenotype_exp1_dir, "green_win_count.tsv", sep = "/"))

blue_win_count_df = merge(exp1_sub_list, blue_win_count_df, by.x = TRUE, all.x = TRUE)
# blue_win_count_df = blue_win_count_df[blue_win_count_df$participant_id %in% mem_sub_list, ]
write_tsv(blue_win_count_df, paste(phenotype_exp1_dir, "blue_win_count.tsv", sep = "/"))

accept_percentage_count_df = merge(exp1_sub_list, accept_percentage_count_df, by.x = TRUE, all.x = TRUE)
# accept_percentage_count_df = accept_percentage_count_df[accept_percentage_count_df$participant_id %in% mem_sub_list, ]
write_tsv(accept_percentage_count_df, paste(phenotype_exp1_dir, "accept_percentage_count.tsv", sep = "/"))

yellow_seen_count_df = merge(exp1_sub_list, yellow_seen_count_df, by.x = TRUE, all.x = TRUE)
# yellow_seen_count_df = yellow_seen_count_df[yellow_seen_count_df$participant_id %in% mem_sub_list, ]
write_tsv(yellow_seen_count_df, paste(phenotype_exp1_dir, "yellow_seen_count.tsv", sep = "/"))
```





